karlicoss/HPI

my/kython/kompress.py
fixes https://github.com/karlicoss/HPI/issues/28
=> Portable CPath

doc/MODULES.org, my/core/__init__.py, my/core/common.py, my/core/init.py, my/kython/konsume.py, my/reading/polar.py, tests/extra/polar.py
Everything should be backwards compatible
=> polar module updates

doc/MODULES.org, doc/SETUP.org, my/hypothesis.py, my/pocket.py
BREAKING CHANGE! You need to:
- clone pockexport (latest version)
- set pockexport path in your config
=> pocket: reuse pockexport data access layer

my/coding/github.py
I use a service called dependabot ( https://dependabot.com/ ).  It
automatically creates pull requests in my repositories to upgrade
dependencies.  The modern front end javascript world moves really
quickly; projects have a ton of dependencies that are updating all the
time, so there are a lot of these pull requests.
Also, the PRs it makes have a lot of info in them.  Here's an example
one: https://github.com/mreishus/spades/pull/180 .  If you hit the
arrows, you can see it includes a lot of text in "Changelog" and
"Commits".  Now check out the list of closed PRs this project has:
https://github.com/mreishus/spades/pulls?q=is%3Apr+is%3Aclosed
Once I got everything working with my.coding.github, my Github.org
(using orger) was huge: 5MB.  I wanted to get rid of the dependabot
stuff, since …
=> my.coding.github ignores some events emitted by bots.

my/pdfs.py
See issue here: https://github.com/karlicoss/HPI/issues/67.
=> Add .get to call for d[date]

doc/SETUP.org
I believe this is the correct command? Thanks!
=> Correct command to create config file

demo.py, doc/MODULES.org, doc/example_config/my/config/__init__.py, my/core/compat.py, my/core/error.py, my/core/warnings.py, my/endomondo.py, my/github/ghexport.py, my/hypothesis.py, my/instapaper.py, my/pocket.py, my/reddit.py, my/rescuetime.py, setup.py, tox.ini
see https://github.com/karlicoss/HPI/issues/79
=> my.hypothesis uses a proper PIP package now

my/core/core_config.py
docs: https://docs.pytest.org/en/stable/warnings.html#warns
=> supress conflicting regex warning

demo.py, doc/SETUP.org, doc/example_config/my/config/repos/hypexport, my/config.py, my/config/__init__.py, my/core/__main__.py, my/core/common.py, my/core/util.py, mypy.ini, setup.py, tests/config.py, tox.ini
(rebased on top of the tz changes)
=> my.config: share stubs for mypy & the example configs + figure out the mess with tox mypy checks

README.org
Similar to Solid, you can put data in a space you control at the outset. Also there is https://0data.app for apps that integrate with Solid and remoteStorage.
=> Add remoteStorage

pytest.ini, tests/README.org, tests/bluemaestro.py, tests/commits.py, tests/common.py, tests/config.py, tests/emfit.py, tests/foursquare.py, tests/github.py, tests/hypothesis.py, tests/instapaper.py, tests/jawbone.py, tests/lastfm.py, tests/orgmode.py, tests/reddit.py, tests/rtm.py, tests/smscalls.py, tests/takeout.py, tests/tweets.py, tests/youtube.py, tox.ini
controllable via HPI_TESTS_KARLICOSS=true
=> tests: more sanity -- run all tests, but exclude tests specific to my computer from CI

my/config.py, my/kobo.py, my/pinboard.py, tox.ini
Use 'hpi module install my.pinboard' to install it
relevant: https://github.com/karlicoss/HPI/issues/79
=> pinboard: *breaking backwards compability*, use pinbexport module directly

my/smscalls.py
so that don't have to infer what
to set in your hpi config based
on usage in module
=> smscalls: add config block

my/coding/commits.py
There was a possibility of repos writing to the same cachew path previously, if a path contained items that weren't in `string.ascii_letters + string.digits`
This just uses the full path in a subdirectory instead
```python
In [5]: from my.coding.commits import _cached_commits_path
In [6]: _cached_commits_path(Path("/home/sean/Repos/HPI"))
Out[6]: '/home/sean/.cache/cachew/my.coding.commits:_cached_commits/home/sean/Repos/HPI'
...
In [10]: !du -h /home/sean/.cache/cachew/my.coding.commits:_cached_commits/home/sean/Repos/HPI/my.coding.commits\:_cached_commits
100K    /home/sean/.cache/cachew/my.coding.commits:_cached_commits/home/sean/Repos/HPI/my.coding.commits:_cached_commits
```
Slightly annoyed that everything is prefixed with your `$HOME` directory, but removing that increases the …
=> commits: reduce possibility of path conflicts

README.org, doc/CONFIGURING.org, doc/CONTRIBUTING.org, doc/DESIGN.org, doc/MODULES.org, doc/MODULE_DESIGN.org, doc/SETUP.org
hope nothing is too far off -- referenced a lot of the issues we've been talking in for the past few months
hopefully nothing broken on the org mode side -- I can now edit org mode as fast as markdown, did take me a while to figure out how links worked though...
now I just need to learn all the keybindings so I'm actually getting benefit out of org
=> add some documentation on module design

my/core/__main__.py
This updates the behaviour when STOUT isn't a TTY:
This would immediately fail if the qualified function couldn't be imported
Follows the interactive behaviour, it tries to import what the user specified as a module, and if theres only one data provider, it selects that
(Modified my `old_forums.py` file to only have one data provider, `my.old_forums.history`)
```
[ ~ ] $ hpi query my.old_forums | jq '.[0]'
{
"dt": "2014-06-21T07:03:00+00:00",
...
```
If theres more than one, I improved the error message it prints out:
```
hpi query my.albums | jq
During fallback, more than one possible data provider, can't prompt since STDOUT is not a TTY
Specify one of:
my.albums.history
my.albums.to_listen
Could not find function 'albums' in 'my'
```
=> cli/query: improve fallback behaviour/error msg

my/core/__main__.py
allows you to do something like
`hpi query --stream my.reddit.comments`
to stream the JSON objects one per line, makes
it nicer to pipe into 'jq'/'fzf' instead
of having to process the giant list
at the end
=> cli/query: add --stream flag

my/core/source.py, my/reddit/__init__.py
just some spelling mistakes I missed
should figure out some way to automatically add stuff to my pre commit hook or something...
=> reddit: fix spelling mistakes

my/reddit/rexport.py
so that HPI_LOGS can be used to interact
with this module, to check if cachew
is working properly
related #187
=> reddit: pass logger to cachew

my/calendar/holidays.py, my/core/common.py, my/core/orgmode.py, my/pdfs.py, my/time/tz/via_location.py, tests/pdfs.py
undoes f5b47dd695fc5abd4aae60a3694a5e7f29099d24 , tests work properly now
resolves https://github.com/karlicoss/HPI/issues/180
=> my.pdf: handle update to pdfannots 0.2

.github/workflows/main.yml, doc/MODULES.org, doc/SETUP.org, my/core/__main__.py, my/core/common.py, my/core/query.py, setup.py
This fixes references to the my.reddit module (often used as an example) in the docs/error message/docstrings
=> core: drop py36 support, update docs for reddit

my/core/__main__.py
adds some short flags as CLI flags for convenience
the --stream flag previously only affected json, but
I can imagine `-o pprint -s -l 5` to print the first
5 items from some function could be useful as well
=> cli/query: add short flags, stream affects pprint

my/reddit/rexport.py
can always be configured with HPI_LOGS
having this on debug makes hpi doctor
quite verbose
=> reddit.rexport: loglevel info by default

my/core/__main__.py
doesn't help in all cases but perhaps helpful anyway
relevant: https://github.com/karlicoss/HPI/issues/109
=> doctor: suggest config documentation in case of ImportError from config

my/config.py, my/instagram/gdpr.py
still somewhat WIP, unclear how to correlate it with android data
=> instagram: initial module for GDPR export

my/fbmessenger/all.py, my/fbmessenger/android.py, my/fbmessenger/common.py, my/fbmessenger/export.py
followup for https://github.com/karlicoss/HPI/pull/179
=> fbmessenger: add all.py, merge messages from different sources

my/core/structure.py
the atexit is a debug log, so it should only warn
if you set `--debug` or `HPI_LOGS` to prevent possible spam
may not by the final version of this, but I think its good
to have this here for debugging purposes anyways
related #213
=> core/structure: use logger, warn leftover files

doc/MODULES.org, my/core/__main__.py, my/core/error.py, my/core/source.py
Solves https://github.com/karlicoss/HPI/issues/223
=> my.config: catch possible nested config errors

my/body/sleep/common.py
seems that the index operator only works when boundaries are in the dataframe
=> my.body.sleep: fix issue with attaching temperature

doc/MODULES.org, my/google/takeout/parser.py
=> docs: add docs for google_takeout_parser

doc/MODULES.org, my/config.py, my/ip/all.py, my/ip/common.py, my/location/all.py, my/location/common.py, my/location/google.py, my/location/google_takeout.py, my/location/gpslogger.py, my/location/home.py, my/location/via_ip.py, my/time/tz/common.py, my/time/tz/via_location.py, tests/tz.py, tox.ini
Should resolve #154
Zulip convo: https://memex.zulipchat.com/#narrow/stream/279601-hpi/topic/locations
Still need to update the docs, but code has been updated -- can take a look at this whenever you're free
CI may fail, made quite a few updates
Still TODO:
=> location: add all.py, using takeout/gpslogger/ip

doc/DENYLIST.md, my/core/__main__.py, my/ip/common.py, tox.ini
pushed denylist [to my branch](https://github.com/seanbreckenridge/HPI-personal/blob/master/my/ip/all.py) now that this is merged here, added that to the docs
just a small fix to link to that and fix module names for `hpi module install` in the CI (didnt do that in the last PR to avoid possible merge conflicts)
=> add example for denylist, update ci

my/smscalls.py
reflects the new types-lxml package
https://github.com/abelcheung/types-lxml
=> smscalls: make some fields optional

doc/SETUP.org, my/bluemaestro.py, my/core/__init__.py, my/core/logging.py, my/github/gdpr.py, my/instagram/android.py, my/instagram/gdpr.py, my/reddit/rexport.py, my/rescuetime.py, my/twitter/archive.py, my/zotero.py, setup.py
see commit messages for more info
=>  core/logging: overhaul and many improvements -- mainly to deprecate abandoned logzero

my/twitter/archive.py
this speeds up processing quite a bit, from 40s to 20s for me, plus removes tons of identical outputs
interesting enough, using raw object without json.dumps as key brings unique_everseen to crawl...
=> twitter.archive: deduplicate results via json.dumps

my/core/_cpu_pool.py, my/reddit/rexport.py
Enabled by the env variable, specifying how many cores to dedicate, e.g.
HPI_CPU_POOL=4 hpi query ...
=> reddit.rexport: experiment with using optional cpu pool (can potentially be used by other HPI modules)

my/core/logging.py
otherwise fails at os.get_terminal_size
=> core.logging: ignore CollapseLogsHandler if we're not attached to a terminal

my/core/init.py
this should help with identifying setup issues
=> core/config: implement a warning if config is imported from the dir other than MY_CONFIG

my/fbmessenger/android.py
seems that threads_db2 stopped updating some time ago, and msys contains all new data now
=> fbmessenger.android: support processing msys database

conftest.py, my/core/tests/test_get_files.py
e.g. pytest --pyargs my.core.tests.test_get_files
=> tests: use updated conftest from pymplate, this allows to run individual test modules properly

my/core/kompress.py, my/github/gdpr.py, my/zulip/organization.py, setup.py
otherwise fall back onto unpacking into tmp dir via my.core.structure
=> my.github.gdpr/my.zulip.organization: use kompress support for tar.gz if it's available

setup.py, tox.ini
see https://github.com/karlicoss/HPI/issues/391
=> tox: some prep for potentially using uv on CI instead of pip

.ci/run, my/core/__main__.py, tox.ini
see https://github.com/karlicoss/HPI/issues/391
=> tox: try using uv for CI, should result in speedup

.github/workflows/main.yml, my/core/__main__.py, my/core/_deprecated/kompress.py, my/core/compat.py, my/core/pandas.py, my/core/utils/concurrent.py, my/youtube/takeout.py, setup.py
=> general: python3.9 reached EOL, switch min version

my/smscalls.py
dont know how I never realized this was missing, adds the phone_number to the `smscalls.Call` model
=> smscalls: add phone number to model

doc/SETUP.org, pyproject.toml, src/my/core/cachew.py, src/my/core/core_config.py, src/my/core/preinit.py
resolves https://github.com/karlicoss/HPI/issues/377
=> core: migrate from deprecated appdirs to platformdirs

src/my/core/common.py
this avoids unnecessary warning when guess_compression=True is used
follow up for https://github.com/karlicoss/HPI/commit/cf8b03131fb1b5bf53f58e83f250d5d39fb7d064
=> core.common: use kompress directly instead of attempting to import previously vendorised version

src/my/core/json.py, src/my/github/gdpr.py, src/my/instagram/android.py, src/my/lastfm.py
=> core: add my.core.json.json_loads, use orjson if available, otherwise fall back to stdlib json

src/my/lastfm.py
- use Protocol based config
- annotate datetime as datetime_aware
- switch to dataclass
=> my.lastfm: some cleanup

src/my/core/experimental.py
This situation is possible under pytest at times... seems easier to just do it than to chase pytest quirks.
Also add some docs for arguments
=> my.core.experimental: some fixes from import_original_module

src/my/coding/commits.py, src/my/core/__init__.py, src/my/core/kompress.py, src/my/github/ghexport.py, src/my/google/maps/android.py, src/my/instagram/gdpr.py, src/my/location/all.py, src/my/location/google_takeout.py, src/my/location/google_takeout_semantic.py, src/my/location/gpslogger.py, src/my/photos/main.py, src/my/roamresearch.py, src/my/twitter/android.py, src/my/twitter/twint.py, src/my/zulip/organization.py
- `my.core.assert_never` in favor of `my.core.compat.assert_never`
- `my.core.LazyLogger` in favor of `my.core.make_logger`
=> core: deprecate my.core.assert_never and my.core.LazyLogger
